### PR TITLE
Fix issue 135

### PR DESCRIPTION
**Pull request by emin63**
Created a fix to issue #135.

The way I solved the problem was to create a method called `_pop_args_for_create_job` to reorganize keywords into the ones that _create_job needs and others to be passed along.

I also added a test script `tests/test_issue_135.py` to verify the fix. I would have added to the existing test script but couldn't get that to work on my end. Feel free to not include test_issue_135.py if you like.

Thanks,
-Emin

### CODE REVIEW

**Comment by antoine-lizee** [comment]
+1 for this.
With the limitation to one scheduler, not being able to specify the `queue_name` in the `enqueue_...()` functions is quite problematic when using several queues.

**Comment by eriktelepovsky** [comment]
+1. I would like to set result_ttl for jobs.

**Comment by Rbeuque74** [comment]
Hello,
Added a pull-request to your branch (https://github.com/emin63/rq-scheduler/pull/1) in order to fix unit-tests issue.

Feel free to ping me if something wrong ;)

**Comment by selwin** [comment]
This is already fixed in the master branch.

**Pull request closed without merging**
