### PR TITLE
Added result_ttl and ttl to cron arguments

### PR DESCRIPTION
**Pull request by marcelblijleven**

### CODE REVIEW

**Comment by selwin** [comment]
Mind mixing the conflict?

**Comment by marcelblijleven** [comment]
> Mind mixing the conflict?

Just updated my branch

**Comment by selwin** [comment]
Thanks!

**Comment by Panayot9** [comment]
Hello @marcelblijleven from the documentation I don't understand if I can set `ttl` in infinite tasks. 

For example:
```python
    scheduler.schedule(
        scheduled_time=datetime.utcnow(),  # Time for first execution, in UTC timezone
        func=func,                           # Function to be queued
        kwargs={'size': 1000},
        interval=6 * 60 * 60,            # Time before the function is called again, in seconds
        repeat=None,                       # Repeat this number of times (None means repeat forever)
        queue_name='default',       # In which queue the job should be put in
        result_ttl=0,                          # Result gets deleted immediately
    )
```

Is this a valid setting? If not what can you suggestion so that I don't store the result in cache.
Thanks in advance!

**Pull request merged**
