### PR TITLE
Removed -q parameter denoting quiet to fix the argument conflict.

### PR DESCRIPTION
**Pull request by sourcepirate**
Fix for issue #179

### CODE REVIEW

**Comment by sourcepirate** [comment]
Since there no -c flag being used. I went with -c flag for --queue-class

**Comment by lariverosc** [comment]
+1 for this to be merged, this issue is breaking the rqscheduler script which doesn't start because of the parameters conflict, please merge and release, thanks :)

**Comment by phwebi** [comment]
Another +1

**Comment by wroscoe** [comment]
+1 @selwin what do you think? This is a fix to the breaking bug in the recent version.

**Comment by Escapingbug** [comment]
Please fix this problem right away. The one on PYPI is now broken because of this.

**Comment by selwin** [comment]
Let's just remove the `-q` shortcut from `--quiet`.

**Comment by sourcepirate** [comment]
@selwin Updated the PR. Is this what you have expected ? 
I would appreciate we can fix this problem as soon as possible.

**Comment by selwin** [comment]
Thanks!

**Comment by selwin** [comment]
0.8.2 is now out on PyPI https://pypi.python.org/pypi/rq-scheduler . Sorry for the delay.

**Comment by sourcepirate** [comment]
@selwin Thank you so much.

**Pull request merged**
