### PR TITLE
Added missing cron arguments

### PR DESCRIPTION
**Pull request by chaffeqa**
* `ttl` default
* `result_ttl` default
* Created line parody with `schedule`

### CODE REVIEW

**Comment by selwin** [comment]
Could you please document the list of accepted arguments in `README`?

**Comment by michalz92** [comment]
I think this is not required in Scheduler.cron():
- `ttl` - this one doesn't make sense here by definition,
- `result_ttl` - this one is not needed, since the job only creates one entry and each run overwrites it (as they share the same job ID)
However, the warning from `worker.py` is pretty confusing. It looks like it can be fixed by not logging the warning if `result_ttl` is equal to -1 (this value is only set by `Scheduler`'s `schedule()` and `cron()` functions).

**Comment by robertaistleitner** [comment]
Since this is pretty outdated but still valid - is there a chance this will be merged @selwin @chaffeqa?

**Comment by selwin** [comment]
I'm ok with merging this in, but needs to be documented :)

**Comment by yurnov** [comment]
Hi @chaffeqa,

could you please update README.md to unlock merging this PR?

**Comment by robhudson** [comment]
This was added in 6e5de20d44111cec374082db3702a50afec86b93

**Pull request closed without merging**
