### PR TITLE
added Dockerfile

### PR DESCRIPTION
**Pull request by AHAPX**
Dockerfile and settings.conf.sample for autobuild docks

### CODE REVIEW

**Comment by selwin** [comment]
I'm not sure why we need to add a Dockerfile for this project. Documenting how we can easily run `rq-scheduler` in docker would be useful though. If you're interested, please add a PR to add this information to README.

**Comment by iddan** [comment]
For most users `rq-scheduler` is just a service that need to be up. Providing a Dockerfile allows users to deploy `rq-scheduler` more easily and sweat less on it's config when there is no need to.

**Comment by antonagestam** [comment]
An official docker image would be really cool! Since the rq-scheduler does not need to run within the same environment or with knowledge of the application it schedules for, I see no reason not to provide an image :)

**Comment by iddan** [comment]
I took up the gauntlet and created an automated build for all the releases.
Docker Hub: https://hub.docker.com/r/iddan/rq-scheduler/tags/
GitHub: https://github.com/iddan/docker-rq-scheduler
TravisCI: https://travis-ci.org/iddan/docker-rq-scheduler

**Pull request closed without merging**
