### PR TITLE
support custom job/queue classes, update rq dependency accordingly

### PR DESCRIPTION
**Pull request by skirsdeda**
This enables custom job/queue classes to be used in scheduler the same way as it is possible in rq (since 0.8). No additional code paths, just changing Job/Queue to swappable attributes, therefore tests should cover this as is.

### CODE REVIEW

**Comment by skirsdeda** [comment]
The last version of rq to support Python 2.6 and 3.0 is rq 0.8.2. Fixed this case in setup.py.

**Comment by selwin** [comment]
@skirsdeda could you please fix the conflicts so I can merge this in?

**Comment by selwin** [comment]
Oh, and could you please document these new kwargs? Thanks!

**Comment by skirsdeda** [comment]
@selwin, that should be it.

**Comment by selwin** [comment]
Thanks!

**Pull request merged**
